### ISSUE TITLE
Problems building from NatNetSDK

### ISSUE THREAD

**Issue by flapjack48** [MOCAP4ROS2-Project/mocap4ros2_optitrack#26]
My lab is working on transitioning to Ros2. 

We are using Ubuntu 22.04 on an OrangePi 5 (arm64) with Ros2 Humble. The build error is from the NatNetSDK portion due to libNatNet.so being in the wrong file format. The following is the output:

Starting >>> mocap_optitrack_driver
Starting >>> rqt_mocap_control
--- stderr: mocap_optitrack_driver                                                                
/usr/bin/ld: /home/darc/darc_ws/src/mocap4ros2_optitrack/mocap_optitrack_driver/NatNetSDK/lib/libNatNet.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/mocap_optitrack_driver_main.dir/build.make:265: mocap_optitrack_driver_main] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:165: CMakeFiles/mocap_optitrack_driver_main.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< mocap_optitrack_driver [19.7s, exited with code 2]
Aborted  <<< rqt_mocap_control [22.2s]                                        

Summary: 8 packages finished [1min 23s]
  1 package failed: mocap_optitrack_driver
  1 package aborted: rqt_mocap_control
  2 packages had stderr output: mocap_optitrack_driver rqt_mocap_control

My question is what system are you using to run the NatNetSDK? The documentation says it should work on Ubuntu but has no other specifics, and all their examples are in Windows. Any help around this would be great. Thanks

**Comment by jmguerreroh** [comment]
Hi @flapjack48 , 

We employ the NatNet SDK on AMD architecture, conducting thorough tests on both Intel i7 and i9 processors. For ARM compatibility, it is advisable to utilize the corresponding libraries. However, since this software originates from Optitrack, we regret to inform you that we are unable to provide assistance in this matter.

Upon researching, I came across a forum post indicating that ARM architecture may not be supported. I recommend reaching out to Optitrack directly and inquiring about any potential solutions for integrating ARM support into our package (https://forums.naturalpoint.com/viewtopic.php?t=20512).

Should you encounter any other issues or require assistance with different concerns, please feel free to contact us again. We are here to help.

Regards.

**Comment by flapjack48** [comment]
Hi @jmguerreroh, 

Thanks for the quick reply. For anyone who comes up with the same problem, I installed the SDK on an AMD64 computer, and that worked great!

**Comment by dvdmc** [comment]
I know this is already answered and out of your reach but, did any of you ever try contacting Optitrack for the binaries? I have seen other posts regarding flying with drones and I think we (including [aerostack2](https://github.com/aerostack2/aerostack2)) are all stuck at the same place. Maybe we can gather some collective effort to ask them :)
